# Generated by Django 2.2.5 on 2019-11-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191111_1024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job',
            new_name='Jobs',
        ),
    ]
